### ISSUE TITLE
Update MME conversion factors (MME IG)

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/opioid-mme-r4#14] opened 2023-01-25 14:46 UTC
Please find a table and notes (including cautions) attached, taken from the 2022 CDC Clinical Practice Guideline. You can locate in the Guideline here - https://www.cdc.gov/mmwr/volumes/71/rr/rr7103a1.htm?s_cid=rr7103a1_w#:~:text=TABLE.%20Morphine%20milligram%20equivalent%20doses%20for%20commonly%20prescribed%20opioids%20for%20pain%20management

[Conversion Factors and Cautions from 2022 CDC Clinical Practice Guideline.docx](https://github.com/cqframework/opioid-mme-r4/files/10500397/Conversion.Factors.and.Cautions.from.2022.CDC.Clinical.Practice.Guideline.docx)

Also, waiting final confirmation from product owners about what cautionary language to include.

**Comment by gregoryawhite** [comment] 2023-01-27 17:04
> Please find a table and notes (including cautions) attached, taken from the 2022 CDC Clinical Practice Guideline. You can locate in the Guideline here - https://www.cdc.gov/mmwr/volumes/71/rr/rr7103a1.htm?s_cid=rr7103a1_w#:~:text=TABLE.%20Morphine%20milligram%20equivalent%20doses%20for%20commonly%20prescribed%20opioids%20for%20pain%20management
> 
> [Conversion Factors and Cautions from 2022 CDC Clinical Practice Guideline.docx](https://github.com/cqframework/opioid-mme-r4/files/10500397/Conversion.Factors.and.Cautions.from.2022.CDC.Clinical.Practice.Guideline.docx)
> 
> Also, waiting final confirmation from product owners about what cautionary language to include.

CDC has confirmed that the conversion factors from the 2022 CDC Clinical Practice Guideline are the ones to be used for updating the CDC MME CQL Calculator IG. Currently, CDC is reviewing the cautionary language that was included with the conversion factors table in the 2022 Guideline and will follow up regarding what cautionary language is to be applied in an updated version of the CDC MME CQL Calculator IG.

**Comment by gregoryawhite** [comment] 2023-02-02 14:25
Here are the MME Cautions that should be used in all IGs that utlized the MME Calculator per CDC:
1) All doses are in mg/day except for fentanyl, which is mcg/hr. 
2) Equianalgesic dose conversions are only estimates and cannot account for individual variability in genetics and pharmacokinetics. 
3) Do not use the calculated dose in MMEs to determine the doses to use when converting one opioid to another; when converting opioids, the new opioid is typically dosed at a substantially lower dose than the calculated MME dose to avoid overdose because of incomplete cross-tolerance and individual variability in opioid pharmacokinetics. Consult the FDA approved product labeling for specific guidance on medications. 
4) Use particular caution with methadone dose conversions because methadone has a long and variable half-life, and peak respiratory depressant effect occurs later and lasts longer than peak analgesic effect. 
5) Use particular caution with transdermal fentanyl because it is dosed in mcg/hr instead of mg/day, and its absorption is affected by heat and other factors. 
6) Buprenorphine products approved for the treatment of pain are not included in the table because of their partial µ-receptor agonist activity and resultant ceiling effects compared with full µ-receptor agonists. 
7) These conversion factors should not be applied to dosage decisions related to the management of opioid use disorder.
† Tapentadol is a µ-receptor agonist and norepinephrine reuptake inhibitor. MMEs are based on degree of µ-receptor agonist activity; however, it is unknown whether tapentadol is associated with overdose in the same dose-dependent manner as observed with medications that are solely µ-receptor agonists.
§ Tramadol is a µ-receptor agonist and norepinephrine and serotonin reuptake inhibitor. MMEs are based on degree of µ-receptor agonist activity; however, it is unknown whether tramadol is associated with overdose in the same dose-dependent manner as observed with medications that are solely µ-receptor agonists.

**Comment by c-schuler** [comment] 2023-03-20 13:43
Update https://github.com/cqframework/opioid-mme-r4/blob/master/input/vocabulary/codesystem/codesystem-CDCMMEClinicalConversionFactors.json

**Comment by gregoryawhite** [comment] 2023-03-20 14:19
Thank You Chris:

Regards,

Greg

**Comment by c-schuler** [comment] 2023-06-01 18:59
Resolved by #15

**Closed as completed by c-schuler** 2023-06-01 18:59 UTC
Labels: enhancement, good first issue
